# Generated by Django 2.2.16 on 2022-05-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220505_0557'),
        ('reviews', '0005_auto_20220504_2232'),
    ]

    operations = [
    ]
