# Generated by Django 2.2.16 on 2022-05-08 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220507_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message="The score can't be less than 1"), django.core.validators.MaxValueValidator(limit_value=10, message="The score can't be greater than 10")]),
        ),
    ]
